import statusList from "./Status";

const myServiceDataSample = [
    {
        id: '2jqwv8nr6e9qwp3v',
        title: '집에서 받는 재활 요가 교실🧘‍♀️',
        name: '오○정',
        img: '/img/profileSample1.png',
        category: '요가',
        type: '정규 클래스',
        region: {
            sido: 11,
            sigugun: 680,
        },
        program: {
            period: 2,
            periodUnit: '개월',
            count: 16,
            price: 350000,
            perTime: 2,
            perTimeUnit: '시간',
            supplies: true,
            disposable: 35000,
            description: '서비스가 진행되는 프로그램 관련 설명을 적는 부분입니다. 해당 칸의 경우 100글자 이상 작성되어야만 정확하게 입력된 것으로 처리하도록 작업해둔 상태이므로, 이에 맞게 100글자 이상 반드시 작성되어야만 합니다.',
        },
        onSale: true,
        serviceNumber: 305344,
        revenue: 332550,
        saleCount: 10,
        sales: [
            {
                price: 350000,
                date: '21.03.30',
                time: '23:06',
                status: statusList.account.end,
                commission: 17500,
            },
            {
                price: 350000,
                date: '21.03.30',
                time: '23:06',
                status: statusList.account.refund,
                commission: 17500,
            },
            {
                price: 350000,
                date: '21.03.30',
                time: '23:06',
                status: statusList.onProgress,
                commission: 17500,
            },
        ],
        recruitType: '개인 레슨',
        account: {
            holder: '오연정',
            bank: '국민은행',
            accountNumber: '12312231323'
        },
    },
    {
        id: 'afwje89a234ansv',
        title: '집에서 받는 재활 요가 교실🧘‍♀️',
        name: '오○정',
        img: '/img/profileSample1.png',
        category: '요가',
        type: '정규 클래스',
        region: {
            sido: 11,
            sigugun: 680,
        },
        program: {
            period: 1,
            periodUnit: '개월',
            count: 10,
            price: 260000,
            perTime: 1,
            perTimeUnit: '시간',
            supplies: true,
            disposable: 26000,
            description: '서비스가 진행되는 프로그램 관련 설명을 적는 부분입니다. 해당 칸의 경우 100글자 이상 작성되어야만 정확하게 입력된 것으로 처리하도록 작업해둔 상태이므로, 이에 맞게 100글자 이상 반드시 작성되어야만 합니다.',
        },
        onSale: false,
        serviceNumber: 30534,
        revenue: 330250,
        saleCount: 9,
        sales: [
            {
                price: 350000,
                date: '21.03.30',
                time: '23:06',
                status: statusList.account.end,
                commission: 17500,
            },
            {
                price: 350000,
                date: '21.03.30',
                time: '23:06',
                status: statusList.account.refund,
                commission: 17500,
            },
            {
                price: 350000,
                date: '21.03.30',
                time: '23:06',
                status: statusList.onProgress,
                commission: 17500,
            },
        ],
        recruitType: '그룹 레슨',
        account: {
            holder: '오연정',
            bank: '국민은행',
            accountNumber: '12312231323'
        },
    },
    {
        id: 'qc3p43nvo3hvn',
        title: '집에서 받는 재활 요가 교실🧘‍♀️',
        name: '오○정',
        img: '/img/profileSample1.png',
        category: '요가',
        type: '정규 클래스',
        region: {
            sido: 11,
            sigugun: 680,
        },
        program: {
            period: 1,
            periodUnit: '개월',
            count: 8,
            price: 180000,
            perTime: 30,
            perTimeUnit: '분',
            supplies: false,
            disposable: 18000,
            description: '서비스가 진행되는 프로그램 관련 설명을 적는 부분입니다. 해당 칸의 경우 100글자 이상 작성되어야만 정확하게 입력된 것으로 처리하도록 작업해둔 상태이므로, 이에 맞게 100글자 이상 반드시 작성되어야만 합니다.',
        },
        onSale: true,
        serviceNumber: 548392,
        revenue: 830000,
        saleCount: 3,
        sales: [
            {
                price: 350000,
                date: '21.03.30',
                time: '23:06',
                status: statusList.account.end,
                commission: 17500,
            },
            {
                price: 350000,
                date: '21.03.30',
                time: '23:06',
                status: statusList.account.refund,
                commission: 17500,
            },
            {
                price: 350000,
                date: '21.03.30',
                time: '23:06',
                status: statusList.onProgress,
                commission: 17500,
            },
        ],
        recruitType: '온라인/화상 레슨',
        account: {
            holder: '오연정',
            bank: '국민은행',
            accountNumber: '12312231323'
        },
    },
];

export default myServiceDataSample;